---
- name: Prepare server, create users and access/permissions framework
  hosts: all
  gather_facts: False
  remote_user: root
  tasks:
    - include: pre_config.yml

- name: Install docker and configure users
  hosts: all
  remote_user: root
  gather_facts: True
  tasks:
    - include: install_docker.yml
    - include: users_ssh_keys_permissions.yml
