---
- hosts: all
  gather_facts: False
  remote_user: root
  pre_tasks:
  - name: Install python 2 for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: output
    changed_when:
      - output.stdout != "" and output.stdout != "\r\n"
  - name: Gathering facts
    setup: # aka gather_facts
  tasks:
  - name: Add 'alec' sudo user
    user:
      name: alec
      password: password
      groups:
        - sudo
      state: present # Tell ansible we want the user to exist.
  - name: Set SSH key for alec user
    authorized_key:
      user: alec
      state: present
      key: "{{ lookup('file', '/Users/aashford/.ssh/id_rsa.pub') }}"
