---
- hosts: all
  gather_facts: False
  remote_user: root
  pre_tasks:
  - name: Install python 2 for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: output
    changed_when:
      - output.stdout != "" and output.stdout != "\r\n"
  - name: Gathering facts
    setup: # aka gather_facts
  tasks:
  - name: Add local current user '{{lookup('env','USER')}}' as sudo user on remote host
    user:
      name: "{{lookup('env','USER')}}"
      password: "$6$MHGI8a4O9gBjmIja$ptiTXls.qDwwOM.FDxh/QFkPyC9d4oF4WMAlXLLPiUtvNG8w9igEbyjN0s1N9/CnMmZTLXiYZRm9vQbNrcNJk/"
      update_password: "always"
      groups:
        - sudo
      state: present # Tell ansible we want the user to exist.
  - name: Set SSH key for the '{{lookup('env','USER')}}' user
    authorized_key:
      user: "{{lookup('env','USER')}}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
